// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Product struct {
	ProductID     int       `gorm:"column:product_id;AUTO_INCREMENT;primary_key"`
	ProductName   string    `gorm:"column:product_name;NOT NULL"`
	Description   string    `gorm:"column:description"`
	Price         string    `gorm:"column:price;NOT NULL"`
	StockQuantity int       `gorm:"column:stock_quantity;NOT NULL"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP"`
}

// SearchProductInput defines the input structure for searching products
type SearchProductInput struct {
	Description string  `form:"description"` // Optional: search by product description
	MinPrice    float64 `form:"min_price"`   // Optional: minimum price
	MaxPrice    float64 `form:"max_price"`   // Optional: maximum price
}

